version: "3"
services:
  server:
    image: node:alpine
    volumes:
      - ./server/:/app
    working_dir: /app
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      SERVER_PORT: 5000
    ports:
      - 5000:5000
    command: npm run dev
  mongo:
    image: mongo  
    expose:
      - 27017
    ports:
    - 50000:27017
    volumes:
      - ./data/db:/data/db
  # webapp-production:
  #   image: nginx
  #   ports:
  #   - 80:80
  #   volumes:
  #   - ./webapp/public:/usr/share/nginx/html
  webapp-dev:
    image: node:alpine
    volumes: 
      - ./webapp/:/app
    working_dir: /app
    depends_on:
      - server
    ports:
      - 8080:3000
    command: npm start
      
